name: Download CS Game Files

on:
  schedule:
  - cron: "0 * * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs: 
    download:
      runs-on: ubuntu-latest
      
      permissions:
        contents: write
      
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v3
        - name: Download new game files
          run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
        - name: Read manifestId.txt
          id: manifestId
          uses: juliangruber/read-file-action@v1
          with:
            path: ./static/manifestId.txt
        - name: Commit & push changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
